Workaround Java 10 Issue /w missing Windows LnF
as of Java 10, com.sun.java.swing.plaf.windows.WindowsLookAndFeel is no longer available on macOS thus "instanceof indowsLookAndFeel" directives will result in a NoClassDefFoundError during runtime and the code will break. The proposed fix works around this problem.